# Generated by Django 5.0 on 2023-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=240)),
                ('Topic', models.CharField(max_length=240)),
                ('content', models.CharField(max_length=2000)),
                ('postDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
