# Generated by Django 5.0 on 2023-12-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Topic',
            new_name='topic',
        ),
    ]
